
service: serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region : us-east-1

functions:
  checkInventory:
    handler: handler.checkInventory
  calculateTotal:
    handler: handler.calculateTotal

plugins : 
  - serverless-step-functions-offline


stepFunctions:
  stateMachines:
    storeCheckoutFlow:
      name: storeCheckoutFlow
      definition:
        StartAt: checkInventory
        States:
          checkInventory:
            Type: Task
            Resource: 
              Fn::GetAtt: [checkInventory,Arn]
            Next: calculateTotal
          calculateTotal:
            Type: Task
            Resource:
              Fn::GetAtt: [calculateTotal,Arn]
            End : true 





